import type { Metadata } from "next";

import "./globals.css";
import { Montserrat } from 'next/font/google';
import { cn } from "./lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const montserrat = Montserrat({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  fallback: ['Arial', 'sans-serif'],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
    className={cn('h-full', montserrat.className)}
      >
        {children}
      </body>
    </html>
  );
}
